# Generated by Django 3.1.5 on 2021-01-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_ingredient_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="CocktailIngredientUnit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(default=1.0, null=True)),
                (
                    "unit_is_displayed",
                    models.BooleanField(default=True, null=True),
                ),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.cocktail",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.ingredient",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.unit",
                    ),
                ),
            ],
        ),
    ]
