# Generated by Django 3.1.5 on 2021-01-27 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210127_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailingredientunit',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_i_u_s', to='app.cocktail'),
        ),
    ]
